import Head from "next/head";
import Link from "next/link";
import Lottie from "lottie-react";
import Presso from "../components/200_200.json";
// import Image from "next/image";
// import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Namju&apos;s Photo Edit Tool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center min-h-screen">
        <h1 className="text-2xl font-bold text-center">
          Hello!
          <br />
          Welcome to Namju&apos;s photo editing tools.
        </h1>

        <section className="m-4">
          <Link href="/stamp" className="">
            Date Stamp
          </Link>
        </section>
      </main>
    </>
  );
}
